arch:
  - arm64
services:
  - docker
before_script:
  - docker pull texlive/texlive
script:
  - docker run --rm --privileged -it -v ${TRAVIS_BUILD_DIR}:/app texlive/texlive /bin/bash -c 'pwd && cd /app && ls -la && make'
  - ls -la
