name: Build CV in PDF

on:
  push:
    branches:
      - master

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Compile the file .tex
      - name: Compile LaTeX document
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error cv.tex
          mv cv.pdf CV_AFRV.pdf

      # Save PDF as artefact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: CV_AFRV.pdf
#curl -X POST \
#  https://api.github.com/repos/AlanVieyra333/curriculum-vitae/releases \
#  -H "Authorization: token c5f1ef50964aaf0a5d7f6ba52f54db659e992999" \
#  -d '{"tag_name":"v1.0"}'
#
#curl -X POST \
#  https://uploads.github.com/repos/AlanVieyra333/curriculum-vitae/releases/33771530/assets?name=CV_AFRV.pdf \
#  -H "Authorization: token c5f1ef50964aaf0a5d7f6ba52f54db659e992999" \
#  -H "Content-Type: application/pdf" \
#  --upload-file CV_AFRV.pdf
